# Generated by Django 5.2.3 on 2025-06-28 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avalia',
            fields=[
                ('id_avalia', models.AutoField(primary_key=True, serialize=False)),
                ('valor_avalia', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id_postagem', models.AutoField(primary_key=True, serialize=False)),
                ('data_postagem', models.DateTimeField(auto_now_add=True)),
                ('titulo_postagem', models.CharField(max_length=255)),
                ('conteudo_postagem', models.TextField()),
                ('autor_postagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postagens', to=settings.AUTH_USER_MODEL)),
                ('id_avalia', models.ForeignKey(blank=True, db_column='id_avalia', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='socialapp.avalia')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('postagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='socialapp.postagem')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('postagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='socialapp.postagem')),
            ],
            options={
                'unique_together': {('usuario', 'postagem')},
            },
        ),
    ]
